players_urls:
  overworld: "MAP URL можно добавь ещё больше миров"

world_bounds:
  xmin: -25000
  xmax: 25000
  zmin: -25000
  zmax: 25000

update_interval: 15
min_request_interval: 5

display:
  head_zorder: 15
  label_zorder: 20
  head_size: 0.15
  head_timeout: 3
  fallback_dot: true
  point_size: 25
  point_color: "#00FF00"
  point_alpha: 0.7
  labels:
    font_size: 8
    text_color: "#FFFF00"
    bg_color: "#000000"
    bg_alpha: 0.5
    y_offset: 8

security:
  admins:
    - "АЙДИ АДМИНА"
  log_file: "security.log"
  alert_on_unauthorized: true

database:
  filename: "activity.db"

telegram:
  token: "ТОКЕН БОТА"
  chat_id: "АЙДИ АДМИНА"
  admin_commands: ["/approve", "/users"]

alerts:
  zones:
    - name: "Спавн"
      bounds: { xmin: -294, xmax: 220, zmin: -252, zmax: 266 }
      allowed_players: []
      alert_level: "INFO"
      cooldown: 30
      excluded: True
      sound: True
      sound_params:
        frequency: 2000
        duration: 1000

    - name: "SlidrusCity"
      bounds: { xmin: -5350, xmax: -2238, zmin: 6346, zmax: 66666 }
      allowed_players:
      -SlidrusForeal
      alert_level: "CRITICAL"
      cooldown: 60
      excluded: False

  limits:
    max_players: 200
    alert_level: "CRITICAL"
  movement_anomaly:
    max_speed: 50
    teleport_threshold: 100
    alert_level: "CRITICAL"
  database:
    filename: "activity.db"
  language: "ru"
  themes:
    default: "dark"

heatmap:
  history_file: "heatmap_history.pkl"
  max_history: 10000000
  bins: 100
  cmap: "hot"
  alpha: 0.7
  mode: "history"
