players_url: "https://map.serverchichi.online/maps/world/live/players.json"
world_bounds:
  xmin: -10145
  xmax: 10145
  zmin: -10078
  zmax: 10078
update_interval: 15
min_request_interval: 5
display:
  point_size: 25
  point_color: "#00FF00"
  point_alpha: 0.7
  labels:
    font_size: 8
    text_color: "#FFFF00"
    bg_color: "#000000"
    bg_alpha: 0.5
    y_offset: 8
alerts:
  zones:
    - name: "Спавн"
      bounds:
        xmin: -500
        xmax: 500
        zmin: -500
        zmax: 500
      alert_level: "INFO"
      cooldown: 30
      excluded: True

    - name: "Сосмарк"
      bounds:
        xmin: 4124
        xmax: 5291
        zmin: -3465
        zmax: -2225
      allowed_players:
        - "K1zik"
        - "Kwakich"
        - "_DeN41k_"
        - "Bruno_Hempf"
        - "Sanplay11"
        - "Panzergrenadier"
        - "napacoJlbka"
        - "Amoliper"
        - "Chestz"
        - "BotEnot"
        - "_mixailchert_"
        - "VuLo4ka"
        - "Aphgust"
        - "Sir_Bred"
        - "Timondarck"
        - "italianopelmen"
        - "KomJys"
        - "BaBiEdA"
        - "poshelyanaher"
        - "Peridotik"
        - "_ChesTer_aD"
        - "RockVandal"
      alert_level: "CRITICAL"
      cooldown: 60
      excluded: False

    # Новые зоны с excluded: True
    - name: "Евгенбург"
      bounds: {xmin: -878, xmax: -282, zmin: 471, zmax: 900}
      alert_level: "INFO"
      cooldown: 60
      excluded: True

    - name: "Redplate"
      bounds: {xmin: 1039, xmax: 1857, zmin: 803, zmax: 1431}
      alert_level: "INFO"
      cooldown: 60
      excluded: True

    - name: "Бодлэнд"
      bounds: {xmin: 1820, xmax: 2250, zmin: 1148, zmax: 1708}
      alert_level: "INFO"
      cooldown: 60
      excluded: True

    - name: "Нексус-9"
      bounds: {xmin: -3230, xmax: -2526, zmin: 4951, zmax: 5594}
      alert_level: "INFO"
      cooldown: 60
      excluded: True

    - name: "Эсторская Республика"
      bounds: {xmin: 5777, xmax: 7079, zmin: -4944, zmax: -4124}
      alert_level: "INFO"
      cooldown: 60
      excluded: True

    - name: "Сайкен"
      bounds: {xmin: -9780, xmax: -9178, zmin: 12, zmax: 990}
      alert_level: "INFO"
      cooldown: 60
      excluded: True

    - name: "Гримбург"
      bounds: {xmin: -4078, xmax: -3193, zmin: -1333, zmax: -539}
      alert_level: "INFO"
      cooldown: 60
      excluded: True

    - name: "Черномория"
      bounds: {xmin: 1996, xmax: 3845, zmin: 3541, zmax: 5907}
      alert_level: "INFO"
      cooldown: 60
      excluded: True

    - name: "СудовАпатов"
      bounds: {xmin: -561, xmax: 345, zmin: -3770, zmax: -2683}
      alert_level: "INFO"
      cooldown: 60
      excluded: True

    - name: "ЧиллХата"
      bounds: {xmin: 4861, xmax: 6082, zmin: -609, zmax: 323}
      alert_level: "INFO"
      cooldown: 60
      excluded: True

    - name: "Город чепуша"
      bounds: {xmin: -3953, xmax: -3373, zmin: -3329, zmax: -2856}
      alert_level: "INFO"
      cooldown: 60
      excluded: True

    - name: "Телория"
      bounds: {xmin: -1642, xmax: -1012, zmin: -1521, zmax: -744}
      alert_level: "INFO"
      cooldown: 60
      excluded: True

    - name: "Мединск"
      bounds: {xmin: -806, xmax: -589, zmin: -322, zmax: 476}
      alert_level: "INFO"
      cooldown: 60
      excluded: True

  limits:
    max_players: 50
    alert_level: "CRITICAL"

  movement_anomaly:  # Новое правило для аномалий перемещения
    alert_level: "CRITICAL"
    cooldown: 300  # 5 минут
    max_speed: 75  # блоков/сек
    teleport_threshold: 500  # блоков

heatmap:
  bins: 100
  cmap: "hot"
  alpha: 0.7
  max_history: 100000
  history_file: "heatmap_history.pkl"
